_ICMP_TYPES = {
	0: "ECHO_REPLY",
	3: "DESTINATION_UNREACHABLE",
	4: "SOURCE_QUENCH",
	5: "REDIRECT_MESSAGE",
	8: "ECHO_REQUEST",
	9: "ROUTER_ADVERTISEMENT",
	10: "ROUTER_SOLICITATION",
	11: "TIME_EXCEEDED"
}


def get_type(pkt):
	return _ICMP_TYPES.get(pkt[20], "UNKNOWN: ".format(pkt[20]))